### ISSUE TITLE
const auto index = is_leaf ? leaves[current].x * 2 + 1 : current * 2;

### ISSUE THREAD

**Issue by Luk0r** [shinjiogaki/bvh#1]
bvh_binary.cpp
line 104
```C++
// leaf/node index
const auto index = is_leaf ? leaves[current].x * 2 + 1 : current * 2;
```
I don't understand this line.
Is the "*2" a left over from the 2d version?

Why not just something like that?
```C++
// leaf/node index
const auto index = is_leaf ? current +1 : current ;
```

**Comment by shinjiogaki** [comment]
> Is the "*2" a left over from the 2d version?
No, it's not. the lowest significant bit is used to specify a leaf or inner node.
(index x 2 means index << 1) 
Please read the comment in the header file.
