### ISSUE TITLE
union の使い方について

### ISSUE THREAD

**Issue by cia-rana** [shinjiogaki/bvh#2]
以下の資料の P53 にある「C++は違う型のunionが許されない」という記載について、[元ソース](http://www.pbr-book.org/3ed-2018/Shapes/Managing_Rounding_Error.html#x1-UtilityRoutines)を見た限り「union で代入したメンバとは違うメンバから値を読み取った場合、値の保証ができない」と言っているだけなので、動作自体はする（資料の書き方でもコンパイルは通る）と思いますが、いかがでしょう？

https://github.com/shinjiogaki/bvh/blob/4250ba1/CEDEC2019.pdf

**Comment by shinjiogaki** [comment]
直しておきます。ありがとうございます。
